### ISSUE TITLE
support redash v10

### ISSUE THREAD

**Issue by akichim21** [render-examples/redash#1]
https://hub.docker.com/r/redash/redash/tags

 redash has released v10.
I tried a little, but I can't access the service (Error 502 gateway error).
Please support v10.

Dockerfile
```
- FROM redash/redash:latest
+ FROM redash/redash:preview
```

error
```
Nov 12 12:47:43 AM  [2021-11-11 15:47:43 +0000] [152] [INFO] Worker exiting (pid: 152)
Nov 12 12:47:43 AM  [2021-11-11 15:47:43 +0000] [155] [ERROR] Exception in worker process
Nov 12 12:47:43 AM  Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/redash/__init__.py", line 56, in <module>
    import_query_runners(settings.QUERY_RUNNERS)
  File "/app/redash/query_runner/__init__.py", line 362, in import_query_runners
    __import__(runner_import)
  File "/app/redash/query_runner/snowflake.py", line 2, in <module>
    import snowflake.connector
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/connection.py", line 44, in <module>
    from .cursor import SnowflakeCursor, LOG_MAX_QUERY_LENGTH
  File "/usr/local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 45, in <module>
    from .arrow_result import ArrowResult
  File "arrow_result.pyx", line 13, in init snowflake.connector.arrow_result
SystemError: initialization of arrow_iterator raised unreported exception

Nov 12 12:47:43 AM  [2021-11-11 15:47:43 +0000] [157] [INFO] Worker exiting (pid: 157)
Nov 12 12:47:43 AM  [2021-11-11 15:47:43 +0000] [155] [INFO] Worker exiting (pid: 155)
Nov 12 12:47:44 AM  [2021-11-11 15:47:44 +0000] [226] [INFO] Booting worker with pid: 226
Nov 12 12:47:44 AM  [2021-11-11 15:47:44 +0000] [227] [INFO] Booting worker with pid: 227
Nov 12 12:47:44 AM  [2021-11-11 15:47:44 +0000] [228] [INFO] Booting worker with pid: 228
Nov 12 12:47:44 AM  [2021-11-11 15:47:44 +0000] [229] [INFO] Booting worker with pid: 229
Nov 12 12:47:44 AM  [2021-11-11 15:47:44 +0000] [230] [INFO] Booting worker with pid: 230
Nov 12 12:47:44 AM  [2021-11-11 15:47:44 +0000] [231] [INFO] Booting worker with pid: 231
Nov 12 12:47:45 AM  [2021-11-11 15:47:45 +0000] [232] [INFO] Booting worker with pid: 232
Nov 12 12:47:45 AM  [2021-11-11 15:47:45 +0000] [233] [INFO] Booting worker with pid: 233
Nov 12 12:48:14 AM  [2021-11-11 15:48:14 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:226)
Nov 12 12:48:14 AM  [2021-11-11 15:48:14 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:227)
Nov 12 12:48:14 AM  [2021-11-11 15:48:14 +0000] [226] [INFO] Worker exiting (pid: 226)
Nov 12 12:48:14 AM  [2021-11-11 15:48:14 +0000] [227] [INFO] Worker exiting (pid: 227)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:228)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:229)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:230)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:231)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:232)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:233)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [228] [INFO] Worker exiting (pid: 228)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [230] [INFO] Worker exiting (pid: 230)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [233] [INFO] Worker exiting (pid: 233)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [229] [INFO] Worker exiting (pid: 229)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [232] [INFO] Worker exiting (pid: 232)
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [298] [INFO] Booting worker with pid: 298
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [299] [INFO] Booting worker with pid: 299
Nov 12 12:48:15 AM  [2021-11-11 15:48:15 +0000] [300] [INFO] Booting worker with pid: 300
Nov 12 12:48:16 AM  [2021-11-11 15:48:16 +0000] [301] [INFO] Booting worker with pid: 301
Nov 12 12:48:16 AM  [2021-11-11 15:48:16 +0000] [302] [INFO] Booting worker with pid: 302
Nov 12 12:48:16 AM  [2021-11-11 15:48:16 +0000] [303] [INFO] Booting worker with pid: 303
Nov 12 12:48:16 AM  [2021-11-11 15:48:16 +0000] [305] [INFO] Booting worker with pid: 305
Nov 12 12:48:16 AM  [2021-11-11 15:48:16 +0000] [304] [INFO] Booting worker with pid: 304
Nov 12 12:47:40 AM  [2021-11-11 15:47:40 +0000] [713] [INFO] Worker exiting (pid: 713)
Nov 12 12:47:40 AM  [2021-11-11 15:47:40 +0000] [708] [INFO] Worker exiting (pid: 708)
Nov 12 12:47:42 AM  [2021-11-11 15:47:42 +0000] [714] [INFO] Worker exiting (pid: 714)
Nov 12 12:47:43 AM  [2021-11-11 15:47:43 +0000] [707] [INFO] Worker exiting (pid: 707)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:298)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:299)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:300)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:301)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:302)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:303)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:304)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:305)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [300] [INFO] Worker exiting (pid: 300)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [302] [INFO] Worker exiting (pid: 302)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [305] [INFO] Worker exiting (pid: 305)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [299] [INFO] Worker exiting (pid: 299)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [303] [INFO] Worker exiting (pid: 303)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [301] [INFO] Worker exiting (pid: 301)
Nov 12 12:48:46 AM  [2021-11-11 15:48:46 +0000] [304] [INFO] Worker exiting (pid: 304)
Nov 12 12:48:47 AM  [2021-11-11 15:48:47 +0000] [298] [INFO] Worker exiting (pid: 298)
Nov 12 12:48:47 AM  [2021-11-11 15:48:47 +0000] [371] [INFO] Booting worker with pid: 371
Nov 12 12:48:47 AM  [2021-11-11 15:48:47 +0000] [372] [INFO] Booting worker with pid: 372
Nov 12 12:48:47 AM  [2021-11-11 15:48:47 +0000] [373] [INFO] Booting worker with pid: 373
Nov 12 12:48:48 AM  [2021-11-11 15:48:48 +0000] [374] [INFO] Booting worker with pid: 374
Nov 12 12:48:48 AM  [2021-11-11 15:48:48 +0000] [375] [INFO] Booting worker with pid: 375
Nov 12 12:48:48 AM  [2021-11-11 15:48:48 +0000] [376] [INFO] Booting worker with pid: 376
Nov 12 12:48:48 AM  [2021-11-11 15:48:48 +0000] [377] [INFO] Booting worker with pid: 377
Nov 12 12:48:48 AM  [2021-11-11 15:48:48 +0000] [378] [INFO] Booting worker with pid: 378
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:371)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:372)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:373)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:374)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:375)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:376)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:377)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:378)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [375] [INFO] Worker exiting (pid: 375)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [378] [INFO] Worker exiting (pid: 378)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [371] [INFO] Worker exiting (pid: 371)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [377] [INFO] Worker exiting (pid: 377)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [373] [INFO] Worker exiting (pid: 373)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [374] [INFO] Worker exiting (pid: 374)
Nov 12 12:49:18 AM  [2021-11-11 15:49:18 +0000] [372] [INFO] Worker exiting (pid: 372)
Nov 12 12:49:19 AM  [2021-11-11 15:49:19 +0000] [376] [INFO] Worker exiting (pid: 376)

```

**Comment by crcastle** [comment]
Thanks for creating this issue @akichim21. I'm seeing the same (or similar) error. I'll see if I can get v10 working on Render and update this repo with the changes.

**Comment by akichim21** [comment]
@crcastle 
Thank you for responding.

**Comment by cjnqt** [comment]
@akichim21  @crcastle  the problem is that the blueprint specify a `standard` web service which has 2 GB of RAM, but Redash v10 requires 4 GB of RAM.

**Comment by pifantastic** [comment]
I'm running into this issue as well.

> @akichim21 @crcastle the problem is that the blueprint specify a `standard` web service which has 2 GB of RAM, but Redash v10 requires 4 GB of RAM.

I've tried upgrading to a Pro instance, but still no luck. I'm actually seeing multiple errors, but I am not sure what is the culprit:

<details>
<summary>
  <code>Exception SystemExit: 1 in &lt;module 'collections' from '/usr/local/lib/python2.7/collections.pyc'&gt; ignored</code>
</summary>
Mar 28 10:33:19 AM  [2022-03-28 14:33:19 +0000] [6725] [INFO] Worker exiting (pid: 6725)
Mar 28 10:33:19 AM  [2022-03-28 14:33:19 +0000] [6709] [INFO] Worker exiting (pid: 6709)
Mar 28 10:33:19 AM  [2022-03-28 14:33:19 +0000] [6708] [INFO] Worker exiting (pid: 6708)
Mar 28 10:33:19 AM  [2022-03-28 14:33:19 +0000] [6717] [INFO] Worker exiting (pid: 6717)
Mar 28 10:33:19 AM  [2022-03-28 14:33:19 +0000] [6707] [INFO] Worker exiting (pid: 6707)
Mar 28 10:33:19 AM  Exception SystemExit: 1 in <module 'collections' from '/usr/local/lib/python2.7/collections.pyc'> ignored
Mar 28 10:33:19 AM  /app/redash/query_runner/cass.py:9: RuntimeWarning: Cython module failed to patch module with custom type
Mar 28 10:33:19 AM    from cassandra.cluster import Cluster
Mar 28 10:33:19 AM  [2022-03-28 14:33:19 +0000] [6710] [INFO] Worker exiting (pid: 6710)
Mar 28 10:33:19 AM  [2022-03-28 14:33:19 +0000] [6712] [INFO] Worker exiting (pid: 6712)
Mar 28 10:33:19 AM  [2022-03-28 14:33:19 +0000] [6722] [INFO] Worker exiting (pid: 6722)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6730)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6731)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6733)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6735)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [6731] [INFO] Worker exiting (pid: 6731)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [6730] [INFO] Worker exiting (pid: 6730)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [6735] [INFO] Worker exiting (pid: 6735)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [6733] [INFO] Worker exiting (pid: 6733)
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7010] [INFO] Booting worker with pid: 7010
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7011] [INFO] Booting worker with pid: 7011
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7012] [INFO] Booting worker with pid: 7012
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7013] [INFO] Booting worker with pid: 7013
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7014] [INFO] Booting worker with pid: 7014
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7015] [INFO] Booting worker with pid: 7015
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7016] [INFO] Booting worker with pid: 7016
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7024] [INFO] Booting worker with pid: 7024
Mar 28 10:33:20 AM  [2022-03-28 14:33:20 +0000] [7026] [INFO] Booting worker with pid: 7026
Mar 28 10:33:21 AM  [2022-03-28 14:33:21 +0000] [7027] [INFO] Booting worker with pid: 7027
Mar 28 10:33:21 AM  [2022-03-28 14:33:21 +0000] [7029] [INFO] Booting worker with pid: 7029
Mar 28 10:33:21 AM  [2022-03-28 14:33:21 +0000] [7031] [INFO] Booting worker with pid: 7031
Mar 28 10:33:21 AM  [2022-03-28 14:33:21 +0000] [7033] [INFO] Booting worker with pid: 7033
Mar 28 10:33:21 AM  [2022-03-28 14:33:21 +0000] [7035] [INFO] Booting worker with pid: 7035
Mar 28 10:33:21 AM  [2022-03-28 14:33:21 +0000] [7036] [INFO] Booting worker with pid: 7036
Mar 28 10:33:21 AM  [2022-03-28 14:33:21 +0000] [7038] [INFO] Booting worker with pid: 7038
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7033)
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7035)
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7036)
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7038)
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [7033] [INFO] Worker exiting (pid: 7033)
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [7036] [INFO] Worker exiting (pid: 7036)
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [7038] [ERROR] Exception in worker process
Mar 28 10:33:52 AM  Traceback (most recent call last):  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker    worker.init_process()  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process    self.load_wsgi()  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi    self.wsgi = self.app.wsgi()  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi    self.callable = self.load()  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load    return self.load_wsgiapp()  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp    return util.import_app(self.app_uri)  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app    __import__(module)  File "/app/redash/__init__.py", line 49, in <module>    import_destinations(settings.DESTINATIONS)  File "/app/redash/destinations/__init__.py", line 81, in import_destinations    __import__(destination_import)  File "/app/redash/destinations/webhook.py", line 7, in <module>    from redash.serializers import serialize_alert  File "/app/redash/serializers/__init__.py", line 15, in <module>    from .query_result import serialize_query_result, serialize_query_result_to_csv, serialize_query_result_to_xlsx  File "/app/redash/serializers/query_result.py", line 8, in <module>    from redash.authentication.org_resolving import current_org  File "/app/redash/authentication/__init__.py", line 13, in <module>    from redash.tasks import record_event  File "/app/redash/tasks/__init__.py", line 1, in <module>    from .general import record_event, version_check, send_mail, sync_user_details  File "/app/redash/tasks/general.py", line 8, in <module>    from redash.worker import celery  File "/app/redash/worker.py", line 7, in <module>    from celery import Celery  File "/usr/local/lib/python2.7/site-packages/celery/local.py", line 509, in __getattr__    module = __import__(self._object_origins[name], None, None, [name])  File "/usr/local/lib/python2.7/site-packages/celery/app/__init__.py", line 10, in <module>    from .base import Celery  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 42, in <module>    from . import builtins  # noqaImportError: cannot import name builtins
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [7038] [INFO] Worker exiting (pid: 7038)
Mar 28 10:33:52 AM  [2022-03-28 14:33:52 +0000] [7035] [INFO] Worker exiting (pid: 7035)
</details>

**Comment by pifantastic** [comment]
Just FYI: I forked this repo and tried deploying Redash using the `redash/redash:8.0.0.b32245` Docker image, but I am actually seeing the same error.

**Comment by akichim21** [comment]
@crcastle @pifantastic 

https://github.com/render-examples/redash/issues/1#issuecomment-1080735992

I encountered the same error.

```
FROM redash/redash:latest

COPY ./render-redash.sh /bin/render-redash
ENTRYPOINT ["/bin/render-redash"]
```

502 Bad Gateway
```
May 4 12:50:36 PM  [2022-05-04 03:50:36 +0000] [5597] [INFO] Booting worker with pid: 5597
May 4 12:50:36 PM  Exception SystemExit: 1 in <module 'collections' from '/usr/local/lib/python2.7/collections.pyc'> ignored
May 4 12:50:36 PM  /usr/local/lib/python2.7/site-packages/pyarrow/__init__.py:54: RuntimeWarning: Cython module failed to patch module with custom type
```

**Comment by akichim21** [comment]
@crcastle 
Is it possible to fix bugs?
I would like to know if there is a way to activate any version of redash.
Thanks.

**Comment by crcastle** [comment]
Hi @akichim21 - Sorry you're having issues with this. I'll take a look at it today or tomorrow.

**Comment by crcastle** [comment]
Hi @akichim21 - Just a quick update: Made some progress on this, but not quite done yet.

**Comment by akichim21** [comment]
@crcastle 
thank you for your response.
very helpful for me.

**Comment by danieljbrooks-GitHub** [comment]
Would also like to use redash on render, but as others have said - no luck. Any progress this week @crcastle?

**Comment by crcastle** [comment]
Hi @danieljbrooks-GitHub and @akichim21 - Update: I should have the upgrade to Redash v10 merged in the next day or two. I was running into some memory issues that were hard to identify initially as memory issues, but all is looking good now.

**Comment by akichim21** [comment]
@crcastle 
Thanks! Let me know when it's done.

**Comment by crcastle** [comment]
Hi @akichim21 and @danieljbrooks-GitHub - I've created a [new branch and PR containing Redash v10](https://github.com/render-examples/redash/pull/3). Would you be able to test it out using the instructions in the PR? Thanks!

**Comment by sonnyp** [comment]
For a lightweight usage, the following works well for us (including emails) - with all services on starter plan.

<details>
  <summary>
    Documentation
  </summary>

# Redash

After the `redash` service is created for the first time, make sure to run the following in the service shell to setup the database.

```sh
render-redash create_db
```

Links:

- https://redash.io/help/open-source/setup
- https://redash.io/help/open-source/admin-guide/env-vars-settings

Inspired by

- https://github.com/render-examples/redash
- https://render.com/docs/deploy-redash
- https://github.com/render-examples/redash/pull/3
- https://github.com/getredash/redash/issues/5640
- [redash docker-compose.yml](https://github.com/getredash/setup/blob/cb47626b6823cbafac407b3e8991e97f53121f6e/data/docker-compose.yml)

</details>

<details>
  <summary>render/Dockerfile</summary>

```
FROM redash/redash:10.1.0.b50633

COPY ./redash/render-redash.sh /bin/render-redash
ENTRYPOINT ["/bin/render-redash"]
```

</details>

<details>
  <summary>redash/render-redash.sh</summary>

```
#!/bin/bash
set -e

export PYTHONUNBUFFERED=1

export REDASH_HOST="redash.example.com"

exec /app/bin/docker-entrypoint "$@"
```

</details>

<details>
  <summary>render.yaml</summary>

```yaml
databases:
  - name: redash postgres14
    region: frankfurt
    plan: Starter
    postgresMajorVersion: 14
    databaseName: redash
    user: redash

services:
  - name: redash
    type: web
    autoDeploy: false
    region: frankfurt
    plan: Starter
    env: docker
    dockerfilePath: ./redash/Dockerfile
    dockerCommand: render-redash server
    healthCheckPath: /ping
    domains:
      - redash.example.com
    envVars:
      - fromGroup: redash
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash postgres14
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          name: redash redis
          type: redis
          property: connectionString
      - key: PORT
        value: 5000
      - key: REDASH_WEB_WORKERS
        value: 1

  - name: redash scheduler
    type: worker
    autoDeploy: false
    region: frankfurt
    plan: Starter
    env: docker
    dockerfilePath: ./redash/Dockerfile
    dockerCommand: render-redash scheduler
    envVars:
      - fromGroup: redash
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash postgres14
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          name: redash redis
          type: redis
          property: connectionString
      - key: QUEUES
        value: "celery"
      - key: WORKERS_COUNT
        value: 1

  - name: redash worker scheduled
    type: worker
    autoDeploy: false
    region: frankfurt
    plan: Starter
    env: docker
    dockerfilePath: ./redash/Dockerfile
    dockerCommand: render-redash worker
    envVars:
      - fromGroup: redash
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash postgres14
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          name: redash redis
          type: redis
          property: connectionString
      - key: QUEUES
        value: "scheduled_queries,schemas"
      - key: WORKERS_COUNT
        value: 1

  - name: redash worker adhoc
    type: worker
    autoDeploy: false
    region: frankfurt
    plan: Starter
    env: docker
    dockerfilePath: ./redash/Dockerfile
    dockerCommand: render-redash worker
    envVars:
      - fromGroup: redash
      - key: REDASH_DATABASE_URL
        fromDatabase:
          name: redash postgres14
          property: connectionString
      - key: REDASH_REDIS_URL
        fromService:
          name: redash redis
          type: redis
          property: connectionString
      - key: QUEUES
        value: "queries,periodic,emails,default"
      - key: WORKERS_COUNT
        value: 1

  - name: redash redis
    type: redis
    region: frankfurt
    plan: Starter
    maxmemoryPolicy: noeviction

envVarGroups:
  - name: redash
    envVars:
      - key: REDASH_LOG_LEVEL
        value: "INFO"
      - key: REDASH_COOKIE_SECRET
        generateValue: true
      - key: REDASH_SECRET_KEY
        generateValue: true
      - key: REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS
        value: true
      - key: REDASH_MAIL_SERVER
        value: smtp.postmarkapp.com
      - key: REDASH_MAIL_PORT
        value: 587
      - key: REDASH_MAIL_USE_TLS
        value: true
      - key: REDASH_MAIL_USERNAME
        sync: false # It is the postmark server "tools" API token
      - key: REDASH_MAIL_PASSWORD
        sync: false # It is the postmark server "tools" API token
      - key: REDASH_MAIL_DEFAULT_SENDER
        value: redash@example.com
```

</details>
